import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { UserDetails } from "@/components/UserDetails/UserDetails";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await UserDetails();

  return (
    <html lang="en">
      <body>
        <Navbar user={user}/>
        {children}
      </body>
    </html>
  );
}
